# Generated by Django 4.1 on 2022-08-17 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='city',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='country',
        ),
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='fly_from',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='fly_to',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='search',
        ),
        migrations.RemoveField(
            model_name='result',
            name='airlines',
        ),
        migrations.RemoveField(
            model_name='result',
            name='fly_from',
        ),
        migrations.RemoveField(
            model_name='result',
            name='fly_to',
        ),
        migrations.RemoveField(
            model_name='result',
            name='search',
        ),
        migrations.RemoveField(
            model_name='search',
            name='fly_from',
        ),
        migrations.RemoveField(
            model_name='search',
            name='fly_to',
        ),
        migrations.RemoveField(
            model_name='search',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='home_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='search.airport'),
        ),
        migrations.DeleteModel(
            name='Airline',
        ),
        migrations.DeleteModel(
            name='Airport',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Flight',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
