# Generated by Django 4.1 on 2022-09-02 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
