CABINS = {
    "Economy": "M",
    "Premium Economy": "W",
    "Business": "C",
    "First": "F",
}

CURRENCIES = {
    "USD": "USD",
    "EUR": "EUR",
    "GBP": "GBP",
    "CAD": "CAD",
    "AUD": "AUD",
    "NZD": "NZD",
    "CHF": "CHF",
    "JPY": "JPY",
    "CNY": "CNY",
    "RUB": "RUB",
    "INR": "INR",
    "BRL": "BRL",
    "SEK": "SEK",
    "DKK": "DKK",
    "NOK": "NOK",
    "PLN": "PLN",
    "MXN": "MXN",
    "CZK": "CZK",
    "HUF": "HUF",
    "PHP": "PHP",
    "ILS": "ILS",
    "ZAR": "ZAR",
    "MYR": "MYR",
    "KRW": "KRW",
    "THB": "THB",
    "IDR": "IDR",
    "TRY": "TRY",
    "RON": "RON",
}
