CABINS = [
    ('M', 'Economy'),
    ('W', 'Premium Economy'),
    ('C', 'Business'),
    ('F', 'First'),
]

CURRENCIES = [
    ("EUR", "Euro"),
    ("USD", "US Dollar"),
    ("GBP", "British Pound"),
    ("AUD", "Australian Dollar"),
    ("CAD", "Canadian Dollar"),
    ("NZD", "New Zealand Dollar"),
    ("CHF", "Swiss Franc"),
    ("SEK", "Swedish Krona"),
    ("DKK", "Danish Krone"),
    ("NOK", "Norwegian Krone"),
    ("JPY", "Japanese Yen"),
    ("MXN", "Mexican Peso"),
    ("BRL", "Brazilian Real"),
    ("CNY", "Chinese Yuan"),
    ("RUB", "Russian Ruble"),
    ("INR", "Indian Rupee"),
    ("KRW", "South Korean Won"),
    ("TRY", "Turkish Lira"),
    ("ZAR", "South African Rand"),
    ("PLN", "Polish Zloty"),
    ("RON", "Romanian Leu"),
    ("HUF", "Hungarian Forint"),
    ("CZK", "Czech Koruna"),
    ("PHP", "Philippine Peso"),
    ("MYR", "Malaysian Ringgit"),
    ("THB", "Thai Baht"),
    ("IDR", "Indonesian Rupiah"),
    ("ISK", "Icelandic Krona"),
    ("BGN", "Bulgarian Lev"),
    ("HRK", "Croatian Kuna"),
    ("RON", "Romanian Leu"),
    ("TRY", "Turkish Lira"),
    ("BRL", "Brazilian Real"),
    ("CNY", "Chinese Yuan"),
]
