# Generated by Django 4.1 on 2022-09-11 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_to', models.PositiveIntegerField(blank=True, null=True)),
                ('curr', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('GBP', 'British Pound'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('NZD', 'New Zealand Dollar'), ('CHF', 'Swiss Franc'), ('SEK', 'Swedish Krona'), ('DKK', 'Danish Krone'), ('NOK', 'Norwegian Krone'), ('JPY', 'Japanese Yen'), ('MXN', 'Mexican Peso'), ('BRL', 'Brazilian Real'), ('CNY', 'Chinese Yuan'), ('RUB', 'Russian Ruble'), ('INR', 'Indian Rupee'), ('KRW', 'South Korean Won'), ('TRY', 'Turkish Lira'), ('ZAR', 'South African Rand'), ('PLN', 'Polish Zloty'), ('RON', 'Romanian Leu'), ('HUF', 'Hungarian Forint'), ('CZK', 'Czech Koruna'), ('PHP', 'Philippine Peso'), ('MYR', 'Malaysian Ringgit'), ('THB', 'Thai Baht'), ('IDR', 'Indonesian Rupiah'), ('ISK', 'Icelandic Krona'), ('BGN', 'Bulgarian Lev'), ('HRK', 'Croatian Kuna'), ('RON', 'Romanian Leu'), ('TRY', 'Turkish Lira'), ('BRL', 'Brazilian Real'), ('CNY', 'Chinese Yuan')], default='EUR', max_length=3)),
                ('email', models.EmailField(max_length=254)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.search')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
