# Generated by Django 4.1 on 2022-09-05 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_remove_airport_city_code_remove_airport_country_code'),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.search'),
        ),
    ]
