# Generated by Django 4.1 on 2022-09-01 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewer', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(max_length=2)),
                ('logo', models.ImageField(blank=True, upload_to='airline_logos')),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('iata_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200, unique=True)),
                ('city_code', models.CharField(blank=True, default=None, max_length=3, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('country_code', models.CharField(blank=True, default=None, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.CharField(max_length=10)),
                ('local_arrival', models.DateTimeField()),
                ('local_departure', models.DateTimeField()),
                ('fare_category', models.CharField(max_length=1)),
                ('segment_no', models.IntegerField()),
                ('return_flight', models.BooleanField()),
                ('airline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.airline')),
                ('fly_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fly_from', to='search.airport')),
                ('fly_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fly_to', to='search.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.CharField(choices=[('fixed', 'Between specified dates'), ('duration', 'By trip duration')], default='strict', max_length=10)),
                ('flight_type', models.CharField(choices=[('round', 'Round trip'), ('oneway', 'One way')], default='round', max_length=10)),
                ('fly_from', models.CharField(max_length=3)),
                ('fly_to', models.CharField(max_length=3)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('flexible', models.IntegerField(choices=[(0, '+- 0 days'), (1, '+- 1 day'), (2, '+- 2 days'), (3, '+- 3 days')], default=0)),
                ('nights_in_dst_from', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30')], default=7)),
                ('nights_in_dst_to', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30')], default=14)),
                ('max_fly_duration', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('adults', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=1)),
                ('children', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=0)),
                ('infants', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=0)),
                ('selected_cabins', models.CharField(choices=[('M', 'Economy'), ('W', 'Premium Economy'), ('C', 'Business'), ('F', 'First')], default='M', max_length=1)),
                ('curr', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('GBP', 'British Pound'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('NZD', 'New Zealand Dollar'), ('CHF', 'Swiss Franc'), ('SEK', 'Swedish Krona'), ('DKK', 'Danish Krone'), ('NOK', 'Norwegian Krone'), ('JPY', 'Japanese Yen'), ('MXN', 'Mexican Peso'), ('BRL', 'Brazilian Real'), ('CNY', 'Chinese Yuan'), ('RUB', 'Russian Ruble'), ('INR', 'Indian Rupee'), ('KRW', 'South Korean Won'), ('TRY', 'Turkish Lira'), ('ZAR', 'South African Rand'), ('PLN', 'Polish Zloty'), ('RON', 'Romanian Leu'), ('HUF', 'Hungarian Forint'), ('CZK', 'Czech Koruna'), ('PHP', 'Philippine Peso'), ('MYR', 'Malaysian Ringgit'), ('THB', 'Thai Baht'), ('IDR', 'Indonesian Rupiah'), ('ISK', 'Icelandic Krona'), ('BGN', 'Bulgarian Lev'), ('HRK', 'Croatian Kuna'), ('RON', 'Romanian Leu'), ('TRY', 'Turkish Lira'), ('BRL', 'Brazilian Real'), ('CNY', 'Chinese Yuan')], default='EUR', max_length=3)),
                ('price_to', models.IntegerField(blank=True, null=True)),
                ('max_stopovers', models.IntegerField(blank=True, choices=[(None, 'Not specified'), (0, 'Direct flights'), (1, 'One stopover'), (2, 'Two stopovers'), (3, 'Three stopovers'), (4, 'Four stopovers')], default=None, null=True)),
                ('limit', models.IntegerField(default=10)),
                ('locale', models.CharField(default='en', max_length=5)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.search')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_duration', models.DurationField()),
                ('return_duration', models.DurationField()),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('departure_arrival_time', models.TimeField()),
                ('return_time', models.TimeField()),
                ('return_arrival_time', models.TimeField()),
                ('has_airport_change', models.BooleanField()),
                ('number_of_stops_departure', models.IntegerField()),
                ('number_of_stops_return', models.IntegerField()),
                ('price', models.IntegerField()),
                ('booking_token', models.CharField(max_length=1000)),
                ('airlines', models.ManyToManyField(to='search.airline')),
                ('connecting_airport_departure', models.ManyToManyField(related_name='connecting_airport_departure', to='search.airport')),
                ('connecting_airport_return', models.ManyToManyField(related_name='connecting_airport_return', to='search.airport')),
                ('flights', models.ManyToManyField(to='search.flight')),
                ('fly_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_origin', to='search.airport')),
                ('fly_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_destination', to='search.airport')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.search')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.search'),
        ),
    ]
