# Generated by Django 4.1 on 2022-08-17 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=2)),
                ('logo', models.ImageField(blank=True, upload_to='airline_logos')),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('iata_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, default=None, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('return_from', models.DateField(blank=True, null=True)),
                ('return_to', models.DateField(blank=True, null=True)),
                ('nights_in_dst_from', models.IntegerField(blank=True, null=True)),
                ('nights_in_dst_to', models.IntegerField(blank=True, null=True)),
                ('max_fly_duration', models.IntegerField(blank=True, null=True)),
                ('flight_type', models.CharField(default='round', max_length=10)),
                ('adults', models.IntegerField(blank=True, default=1, null=True)),
                ('children', models.IntegerField(blank=True, default=0)),
                ('infants', models.IntegerField(blank=True, default=0)),
                ('selected_cabins', models.CharField(choices=[('M', 'Economy'), ('W', 'Premium Economy'), ('C', 'Business'), ('F', 'First')], default='M', max_length=1)),
                ('mix_with_cabins', models.CharField(blank=True, choices=[('M', 'Economy'), ('W', 'Premium Economy'), ('C', 'Business'), ('F', 'First')], max_length=5, null=True)),
                ('curr', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('GBP', 'British Pound'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('NZD', 'New Zealand Dollar'), ('CHF', 'Swiss Franc'), ('SEK', 'Swedish Krona'), ('DKK', 'Danish Krone'), ('NOK', 'Norwegian Krone'), ('JPY', 'Japanese Yen'), ('MXN', 'Mexican Peso'), ('BRL', 'Brazilian Real'), ('CNY', 'Chinese Yuan'), ('RUB', 'Russian Ruble'), ('INR', 'Indian Rupee'), ('KRW', 'South Korean Won'), ('TRY', 'Turkish Lira'), ('ZAR', 'South African Rand'), ('PLN', 'Polish Zloty'), ('RON', 'Romanian Leu'), ('HUF', 'Hungarian Forint'), ('CZK', 'Czech Koruna'), ('PHP', 'Philippine Peso'), ('MYR', 'Malaysian Ringgit'), ('THB', 'Thai Baht'), ('IDR', 'Indonesian Rupiah'), ('ISK', 'Icelandic Krona'), ('BGN', 'Bulgarian Lev'), ('HRK', 'Croatian Kuna'), ('RON', 'Romanian Leu'), ('TRY', 'Turkish Lira'), ('BRL', 'Brazilian Real'), ('CNY', 'Chinese Yuan')], default='EUR', max_length=3)),
                ('price_from', models.IntegerField(blank=True, null=True)),
                ('price_to', models.IntegerField(blank=True, null=True)),
                ('max_stopovers', models.IntegerField(blank=True, null=True)),
                ('limit', models.IntegerField(default=100)),
                ('fly_from', models.ManyToManyField(related_name='flight_origin', to='search.airport')),
                ('fly_to', models.ManyToManyField(related_name='flight_destination', to='search.airport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_duration', models.IntegerField()),
                ('return_duration', models.IntegerField()),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('return_time', models.TimeField()),
                ('has_airport_change', models.BooleanField()),
                ('number_of_stops', models.IntegerField()),
                ('price', models.IntegerField()),
                ('bags_price', models.CharField(max_length=100)),
                ('availability', models.IntegerField()),
                ('deep_link', models.CharField(max_length=500)),
                ('airlines', models.ManyToManyField(to='search.airline')),
                ('fly_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_origin', to='search.airport')),
                ('fly_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_destination', to='search.airport')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.search')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.CharField(max_length=10)),
                ('local_arrival', models.DateTimeField()),
                ('local_departure', models.DateTimeField()),
                ('fare_category', models.CharField(max_length=1)),
                ('segment_no', models.IntegerField()),
                ('return_flight', models.BooleanField()),
                ('airline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.airline')),
                ('fly_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fly_from', to='search.airport')),
                ('fly_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fly_to', to='search.airport')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.search')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, default=None, max_length=3)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.country')),
            ],
        ),
        migrations.AddField(
            model_name='airport',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.city'),
        ),
        migrations.AddField(
            model_name='airport',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.country'),
        ),
    ]
