# Generated by Django 4.1 on 2022-09-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='flexible',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='nights_in_dst_from',
            field=models.PositiveIntegerField(blank=True, default=7, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='nights_in_dst_to',
            field=models.PositiveIntegerField(blank=True, default=14, null=True),
        ),
    ]
