# Generated by Django 4.1 on 2022-09-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='city_code',
            field=models.CharField(default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='country_code',
            field=models.CharField(default=None, max_length=2, null=True),
        ),
    ]
