# Generated by Django 4.1 on 2022-09-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_airport_city_code_alter_airport_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='city',
            field=models.CharField(max_length=200),
        ),
    ]
