# Generated by Django 4.1 on 2022-09-09 16:08

from django.db import migrations, models
import django.db.models.deletion
import search.models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_search_fly_from_search_fly_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='price_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='fly_from',
            field=search.models.AirportField(on_delete=django.db.models.deletion.CASCADE, related_name='flight_fly_from', to='search.airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='fly_to',
            field=search.models.AirportField(on_delete=django.db.models.deletion.CASCADE, related_name='flight_fly_to', to='search.airport'),
        ),
        migrations.AlterField(
            model_name='search',
            name='adults',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='search',
            name='children',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='search',
            name='flexible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='search',
            name='infants',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='search',
            name='nights_in_dst_from',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='search',
            name='nights_in_dst_to',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='search',
            name='search_type',
            field=models.CharField(choices=[('fixed', 'By dates'), ('duration', 'By duration')], default='strict', max_length=10),
        ),
    ]
