# Generated by Django 4.1 on 2022-09-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_airport_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='fly_from',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='search',
            name='fly_to',
            field=models.CharField(max_length=20),
        ),
    ]
