# Generated by Django 4.1 on 2022-09-10 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_search_price_from_alter_flight_fly_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='fly_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_fly_from', to='search.airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='fly_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_fly_to', to='search.airport'),
        ),
    ]
