# Generated by Django 4.1 on 2022-09-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_flight_fly_from_alter_flight_fly_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='fly_from',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='search',
            name='fly_to',
            field=models.CharField(max_length=100),
        ),
    ]
