# Generated by Django 4.1 on 2022-09-02 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0004_alter_search_fly_from_alter_search_fly_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='limit',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='search',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
