# Generated by Django 4.1 on 2022-09-02 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_alter_search_limit_alter_search_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
