# Generated by Django 4.1 on 2022-09-10 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_alter_search_fly_from_alter_search_fly_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='fly_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_fly_from', to='search.airport'),
        ),
        migrations.AlterField(
            model_name='search',
            name='fly_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_fly_to', to='search.airport'),
        ),
    ]
