# Generated by Django 4.1 on 2022-09-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_alter_airline_iata_code_alter_search_departure_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='limit',
            field=models.IntegerField(default=5),
        ),
    ]
