# Generated by Django 4.1 on 2022-09-04 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_delete_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='city_code',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='country_code',
        ),
    ]
